version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y python3-virtualenv
      - python3 -m venv test_venv
      - . test_venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - rm -rf dspt
      - mkdir test-reports
  build:
    commands:
      - pytest 
        --html=test-reports/report.html 
        --self-contained-html
        -s
        -v
        --cov=dspt 
        --cov-report=html:test-reports/coverage 
        --log-file=test-reports/logs.txt 
        tests      
  post_build:
    commands:
      - echo Build completed on `date`
      - rm -rf test_venv

artifacts:
  files:
    - '**/*'
    - Procfile
  discard-paths: no